# nn.Module i nn.Linear

In [1]:
import torch
import torch.nn as nn

from tqdm import tqdm

In [ ]:
class LinearRegression(nn.Module):
    def __init__(self):
        super().__init__()

        self.linear = nn.Linear(1,1)
    
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.linear(x)

In [3]:
x = torch.randn(100,1)
noise = torch.randn(100,1) * 0.1

print(x[:5])
print(noise[:5])

tensor([[-0.4874],
        [-0.0232],
        [-0.6976],
        [-0.1212],
        [-1.5279]])
tensor([[ 0.0751],
        [ 0.0063],
        [ 0.0809],
        [ 0.1514],
        [-0.0964]])


In [4]:
y = 2 * x + 1 + noise
y[:5]

tensor([[ 0.1004],
        [ 0.9598],
        [-0.3143],
        [ 0.9091],
        [-2.1522]])

In [5]:
model = LinearRegression()
loss_fn = nn.MSELoss()

In [6]:
n_epochs = 1000

for epoch in tqdm(range(n_epochs)):
    model.train()
    yhat = model(x)

    loss = loss_fn(yhat,y)

    loss.backward()

    with torch.inference_mode():
        for param in model.parameters():
            if param.grad is not None:
                param -= 0.01 * param.grad

        model.zero_grad()
    if epoch % 100 == 0:
        print(f"Epoch: {epoch}, Loss: {loss.item():.4f}")



  0%|          | 0/1000 [00:00<?, ?it/s]


RuntimeError: mat1 and mat2 shapes cannot be multiplied (100x1 and 3x1)

In [ ]:
model.state_dict()

OrderedDict([('linear.weight', tensor([[2.0003]])),
             ('linear.bias', tensor([1.0023]))])